// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-place.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var NAIROBI_VIEWBOX = "36.6509,-1.1638,37.1035,-1.4442";
var search_place_default = defineTool({
  name: "search_place",
  title: "Search Nairobi place",
  description: "Search for a place, address, or landmark in Nairobi, Kenya. Returns matching locations with coordinates. Use this to resolve a place name to lat/lng.",
  inputSchema: {
    query: z.string().min(1).describe("Place name, address, or landmark in Nairobi (e.g. 'Westgate Mall', 'JKIA')."),
    limit: z.number().int().min(1).max(10).optional().describe("Max results, default 5.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ query, limit }) => {
    const url = new URL("https://nominatim.openstreetmap.org/search");
    url.searchParams.set("q", query);
    url.searchParams.set("format", "json");
    url.searchParams.set("viewbox", NAIROBI_VIEWBOX);
    url.searchParams.set("bounded", "1");
    url.searchParams.set("limit", String(limit ?? 5));
    url.searchParams.set("countrycodes", "ke");
    const res = await fetch(url.toString(), {
      headers: { "User-Agent": "wayfinder-africa-mcp/0.1 (nairobi navigation)" }
    });
    if (!res.ok) {
      return { content: [{ type: "text", text: `Nominatim error: ${res.status}` }], isError: true };
    }
    const raw = await res.json();
    const results = raw.map((r) => ({
      name: r.display_name,
      lat: parseFloat(r.lat),
      lng: parseFloat(r.lon),
      type: r.type
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { results }
    };
  }
});

// src/lib/mcp/tools/get-route.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_route_default = defineTool2({
  name: "get_route",
  title: "Get driving route",
  description: "Compute a driving route between two coordinates in/around Nairobi using OSRM. Returns distance (meters), duration (seconds), and turn-by-turn steps.",
  inputSchema: {
    originLat: z2.number().describe("Origin latitude."),
    originLng: z2.number().describe("Origin longitude."),
    destinationLat: z2.number().describe("Destination latitude."),
    destinationLng: z2.number().describe("Destination longitude."),
    alternatives: z2.boolean().optional().describe("Include alternative routes (up to 3). Default false.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ originLat, originLng, destinationLat, destinationLng, alternatives }) => {
    const coords = `${originLng},${originLat};${destinationLng},${destinationLat}`;
    const url = `https://router.project-osrm.org/route/v1/driving/${coords}?overview=false&steps=true&alternatives=${alternatives ? "true" : "false"}`;
    const res = await fetch(url);
    if (!res.ok) {
      return { content: [{ type: "text", text: `OSRM error: ${res.status}` }], isError: true };
    }
    const data = await res.json();
    if (!data.routes?.length) {
      return { content: [{ type: "text", text: "No route found." }], isError: true };
    }
    const routes = data.routes.map((r) => ({
      distanceMeters: r.distance,
      distanceKm: +(r.distance / 1e3).toFixed(2),
      durationSeconds: r.duration,
      durationMinutes: +(r.duration / 60).toFixed(1),
      steps: r.legs.flatMap((l) => l.steps).map((s) => ({
        road: s.name || "",
        distance: s.distance,
        duration: s.duration,
        maneuver: s.maneuver?.type,
        modifier: s.maneuver?.modifier
      }))
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(routes, null, 2) }],
      structuredContent: { routes }
    };
  }
});

// src/lib/mcp/tools/estimate-fuel-cost.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var FUEL_PRICE_KSH_PER_L = 195;
var CONSUMPTION_L_PER_KM = 0.1;
var estimate_fuel_cost_default = defineTool3({
  name: "estimate_fuel_cost",
  title: "Estimate fuel cost",
  description: "Estimate fuel cost in Kenyan Shillings (Ksh) for a given driving distance in kilometers, using Nairobi average fuel price and consumption (~10 km/L, Ksh 195/L).",
  inputSchema: {
    distanceKm: z3.number().positive().describe("Trip distance in kilometers."),
    consumptionLPer100Km: z3.number().positive().optional().describe("Optional vehicle consumption in L/100km. Defaults to 10 L/100km."),
    fuelPriceKshPerL: z3.number().positive().optional().describe("Optional fuel price in Ksh per litre. Defaults to 195.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ distanceKm, consumptionLPer100Km, fuelPriceKshPerL }) => {
    const consumption = consumptionLPer100Km ? consumptionLPer100Km / 100 : CONSUMPTION_L_PER_KM;
    const price = fuelPriceKshPerL ?? FUEL_PRICE_KSH_PER_L;
    const litres = +(distanceKm * consumption).toFixed(2);
    const costKsh = Math.round(litres * price);
    return {
      content: [
        {
          type: "text",
          text: `Estimated ${litres} L, ~Ksh ${costKsh} for ${distanceKm} km at Ksh ${price}/L.`
        }
      ],
      structuredContent: { distanceKm, litres, costKsh, fuelPriceKshPerL: price }
    };
  }
});

// src/lib/mcp/tools/reverse-geocode.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
var reverse_geocode_default = defineTool4({
  name: "reverse_geocode",
  title: "Reverse geocode",
  description: "Convert latitude/longitude coordinates into a human-readable Nairobi/Kenya address or place name.",
  inputSchema: {
    lat: z4.number().describe("Latitude."),
    lng: z4.number().describe("Longitude.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ lat, lng }) => {
    const url = `https://nominatim.openstreetmap.org/reverse?lat=${lat}&lon=${lng}&format=json`;
    const res = await fetch(url, {
      headers: { "User-Agent": "wayfinder-africa-mcp/0.1 (nairobi navigation)" }
    });
    if (!res.ok) {
      return { content: [{ type: "text", text: `Nominatim error: ${res.status}` }], isError: true };
    }
    const data = await res.json();
    return {
      content: [{ type: "text", text: data.display_name ?? "Unknown location" }],
      structuredContent: { name: data.display_name, address: data.address, lat, lng }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "wayfinder-africa-mcp",
  title: "Wayfinder Africa",
  version: "0.1.0",
  instructions: "Nairobi-focused navigation tools: search Kenyan places (search_place), compute driving routes with OSRM (get_route), reverse-geocode coordinates (reverse_geocode), and estimate fuel costs in Ksh (estimate_fuel_cost). Use search_place first to turn a place name into coordinates, then pass those to get_route.",
  tools: [search_place_default, get_route_default, reverse_geocode_default, estimate_fuel_cost_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
